import './globals.css'
import { Rubik } from 'next/font/google'

// components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// children prop refers to whatever content this component might wrap
// in nextjs, layout components wrap page components
// children in this case refers to the page component being viewed in the browser, which will change as the user navigates to different pages
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  )
}
